export const REQUEST_USER_DASHBOARD = "REQUEST_USER_DASHBOARD";
export const SUCCESS_USER_DASHBOARD = "SUCCESS_USER_DASHBOARD";
export const FAILED_USER_DASHBOARD = "FAILED_USER_DASHBOARD";
export const REQUEST_USER_CASHBACK_SUMMARY = "REQUEST_USER_CASHBACK_SUMMARY";
export const SUCCESS_USER_CASHBACK_SUMMARY = "SUCCESS_USER_CASHBACK_SUMMARY";
export const FAILED_USER_CASHBACK_SUMMARY = "FAILED_USER_CASHBACK_SUMMARY";
export const REQUEST_USER_BONUS_SUMMARY = "REQUEST_USER_BONUS_SUMMARY";
export const SUCCESS_USER_BONUS_SUMMARY = "SUCCESS_USER_BONUS_SUMMARY";
export const FAILED_USER_BONUS_SUMMARY = "FAILED_USER_BONUS_SUMMARY";
export const REQUEST_USER_REFERRAL_SUMMARY = "REQUEST_USER_REFERRAL_SUMMARY";
export const SUCCESS_USER_REFERRAL_SUMMARY = "SUCCESS_USER_REFERRAL_SUMMARY";
export const FAILED_USER_REFERRAL_SUMMARY = "FAILED_USER_REFERRAL_SUMMARY";
export const REQUEST_USER_CLICKS_SUMMARY = "REQUEST_USER_CLICKS_SUMMARY";
export const SUCCESS_USER_CLICKS_SUMMARY = "SUCCESS_USER_CLICKS_SUMMARY";
export const FAILED_USER_CLICKS_SUMMARY = "FAILED_USER_CLICKS_SUMMARY";
export const REQUEST_USER_ACTIVITY_CASHBACK = "REQUEST_USER_ACTIVITY_CASHBACK";
export const SUCCESS_USER_ACTIVITY_CASHBACK = "SUCCESS_USER_ACTIVITY_CASHBACK";
export const FAILED_USER_ACTIVITY_CASHBACK = "FAILED_USER_ACTIVITY_CASHBACK";
export const REQUEST_USER_ACTIVITY_BONUS = "REQUEST_USER_ACTIVITY_BONUS";
export const SUCCESS_USER_ACTIVITY_BONUS = "SUCCESS_USER_ACTIVITY_BONUS";
export const FAILED_USER_ACTIVITY_BONUS = "FAILED_USER_ACTIVITY_BONUS";
export const REQUEST_USER_ACTIVITY_REFERRAL = "REQUEST_USER_ACTIVITY_REFERRAL";
export const SUCCESS_USER_ACTIVITY_REFERRAL = "SUCCESS_USER_ACTIVITY_REFERRAL";
export const FAILED_USER_ACTIVITY_REFERRAL = "FAILED_USER_ACTIVITY_REFERRAL";
export const REQUEST_USER_ACTIVITY_CLICKS = "REQUEST_USER_ACTIVITY_CLICKS";
export const SUCCESS_USER_ACTIVITY_CLICKS = "SUCCESS_USER_ACTIVITY_CLICKS";
export const FAILED_USER_ACTIVITY_CLICKS = "FAILED_USER_ACTIVITY_CLICKS";
export const REQUEST_USER_ACTIVITY_CLICKS_RECENT =
  "REQUEST_USER_ACTIVITY_CLICKS_RECENT";
export const SUCCESS_USER_ACTIVITY_CLICKS_RECENT =
  "SUCCESS_USER_ACTIVITY_CLICKS_RECENT";
export const FAILED_USER_ACTIVITY_CLICKS_RECENT =
  "FAILED_USER_ACTIVITY_CLICKS_RECENT";
export const REQUEST_USER_CLAIM_LIST = "REQUEST_USER_CLAIM_LIST";
export const SUCCESS_USER_CLAIM_LIST = "SUCCESS_USER_CLAIM_LIST";
export const FAILED_USER_CLAIM_LIST = "FAILED_USER_CLAIM_LIST";
export const REQUEST_CLAIM_INFO = "REQUEST_CLAIM_INFO";
export const SUCCESS_CLAIM_INFO = "SUCCESS_CLAIM_INFO";
export const FAILED_CLAIM_INFO = "FAILED_CLAIM_INFO";
export const REQUEST_USER_CLAIM_CLOSE = "REQUEST_USER_CLAIM_CLOSE";
export const SUCCESS_USER_CLAIM_CLOSE = "SUCCESS_USER_CLAIM_CLOSE";
export const FAILED_USER_CLAIM_CLOSE = "FAILED_USER_CLAIM_CLOSE";
export const REQUEST_USER_CLAIM_POST_COMMENT =
  "REQUEST_USER_CLAIM_POST_COMMENT";
export const SUCCESS_USER_CLAIM_POST_COMMENT =
  "SUCCESS_USER_CLAIM_POST_COMMENT";
export const FAILED_USER_CLAIM_POST_COMMENT = "FAILED_USER_CLAIM_POST_COMMENT";
export const REQUEST_USER_CLAIM_STORES = "REQUEST_USER_CLAIM_STORES";
export const SUCCESS_USER_CLAIM_STORES = "SUCCESS_USER_CLAIM_STORES";
export const FAILED_USER_CLAIM_STORES = "FAILED_USER_CLAIM_STORES";
export const REQUEST_USER_CLAIM_STORE_CLICKS =
  "REQUEST_USER_CLAIM_STORE_CLICKS";
export const SUCCESS_USER_CLAIM_STORE_CLICKS =
  "SUCCESS_USER_CLAIM_STORE_CLICKS";
export const FAILED_USER_CLAIM_STORE_CLICKS = "FAILED_USER_CLAIM_STORE_CLICKS";
export const REQUEST_CLAIM_MAKE = "REQUEST_CLAIM_MAKE";
export const SUCCESS_CLAIM_MAKE = "SUCCESS_CLAIM_MAKE";
export const FAILED_CLAIM_MAKE = "FAILED_CLAIM_MAKE";
export const REQUEST_USER_PAYMENT_LIST = "REQUEST_USER_PAYMENT_LIST";
export const SUCCESS_USER_PAYMENT_LIST = "SUCCESS_USER_PAYMENT_LIST";
export const FAILED_USER_PAYMENT_LIST = "FAILED_USER_PAYMENT_LIST";
export const REQUEST_USER_PAYMENT_METHODS = "REQUEST_USER_PAYMENT_METHODS";
export const SUCCESS_USER_PAYMENT_METHODS = "SUCCESS_USER_PAYMENT_METHODS";
export const FAILED_USER_PAYMENT_METHODS = "FAILED_USER_PAYMENT_METHODS";
export const REQUEST_USER_PAYMENT_ADD_METHOD =
  "REQUEST_USER_PAYMENT_ADD_METHOD";
export const SUCCESS_USER_PAYMENT_ADD_METHOD =
  "SUCCESS_USER_PAYMENT_ADD_METHOD";
export const FAILED_USER_PAYMENT_ADD_METHOD = "FAILED_USER_PAYMENT_ADD_METHOD";
export const REQUEST_USER_PAYMENT_REQUEST = "REQUEST_USER_PAYMENT_REQUEST";
export const SUCCESS_USER_PAYMENT_REQUEST = "SUCCESS_USER_PAYMENT_REQUEST";
export const FAILED_USER_PAYMENT_REQUEST = "FAILED_USER_PAYMENT_REQUEST";
export const REQUEST_USER_REFERRAL_LIST = "REQUEST_USER_REFERRAL_LIST";
export const SUCCESS_USER_REFERRAL_LIST = "SUCCESS_USER_REFERRAL_LIST";
export const FAILED_USER_REFERRAL_LIST = "FAILED_USER_REFERRAL_LIST";
export const REQUEST_USER_REFERRAL_INVITES = "REQUEST_USER_REFERRAL_INVITES";
export const SUCCESS_USER_REFERRAL_INVITES = "SUCCESS_USER_REFERRAL_INVITES";
export const FAILED_USER_REFERRAL_INVITES = "FAILED_USER_REFERRAL_INVITES";
export const REQUEST_USER_REFERRAL_INVITE = "REQUEST_USER_REFERRAL_INVITE";
export const SUCCESS_USER_REFERRAL_INVITE = "SUCCESS_USER_REFERRAL_INVITE";
export const FAILED_USER_REFERRAL_INVITE = "FAILED_USER_REFERRAL_INVITE";
export const REQUEST_USER_LINK_LIST = "REQUEST_USER_LINK_LIST";
export const SUCCESS_USER_LINK_LIST = "SUCCESS_USER_LINK_LIST";
export const FAILED_USER_LINK_LIST = "FAILED_USER_LINK_LIST";
export const REQUEST_USER_LINK_CREATE = "REQUEST_USER_LINK_CREATE";
export const SUCCESS_USER_LINK_CREATE = "SUCCESS_USER_LINK_CREATE";
export const FAILED_USER_LINK_CREATE = "FAILED_USER_LINK_CREATE";
export const REQUEST_USER_MODULE_INFO = "REQUEST_USER_MODULE_INFO";
export const SUCCESS_USER_MODULE_INFO = "SUCCESS_USER_MODULE_INFO";
export const FAILED_USER_MODULE_INFO = "FAILED_USER_MODULE_INFO";
export const REQUEST_USER_MODULES = "REQUEST_USER_MODULES";
export const SUCCESS_USER_MODULES = "SUCCESS_USER_MODULES";
export const FAILED_USER_MODULES = "FAILED_USER_MODULES";
export const REQUEST_USER_PAYMENT_SUMMARY = "REQUEST_USER_PAYMENT_SUMMARY";
export const SUCCESS_USER_PAYMENT_SUMMARY = "SUCCESS_USER_PAYMENT_SUMMARY";
export const FAILED_USER_PAYMENT_SUMMARY = "FAILED_USER_PAYMENT_SUMMARY";
export const REQUEST_USER_FAVS = "REQUEST_USER_FAVS";
export const SUCCESS_USER_FAVS = "SUCCESS_USER_FAVS";
export const FAILED_USER_FAVS = "FAILED_USER_FAVS";
export const REQUEST_USER_ADD_FAV = "REQUEST_USER_ADD_FAV";
export const SUCCESS_USER_ADD_FAV = "SUCCESS_USER_ADD_FAV";
export const FAILED_USER_ADD_FAV = "FAILED_USER_ADD_FAV";
export const REQUEST_USER_REMOVE_FAV = "REQUEST_USER_REMOVE_FAV";
export const SUCCESS_USER_REMOVE_FAV = "SUCCESS_USER_REMOVE_FAV";
export const FAILED_USER_REMOVE_FAV = "FAILED_USER_REMOVE_FAV";
export const REQUEST_USER_CHANGE_NAME = "REQUEST_USER_CHANGE_NAME";
export const SUCCESS_USER_CHANGE_NAME = "SUCCESS_USER_CHANGE_NAME";
export const FAILED_USER_CHANGE_NAME = "FAILED_USER_CHANGE_NAME";
export const REQUEST_USER_CHANGE_LANG = "REQUEST_USER_CHANGE_LANG";
export const SUCCESS_USER_CHANGE_LANG = "SUCCESS_USER_CHANGE_LANG";
export const FAILED_USER_CHANGE_LANG = "FAILED_USER_CHANGE_LANG";
export const REQUEST_USER_CHANGE_PASSWORD = "REQUEST_USER_CHANGE_PASSWORD";
export const SUCCESS_USER_CHANGE_PASSWORD = "SUCCESS_USER_CHANGE_PASSWORD";
export const FAILED_USER_CHANGE_PASSWORD = "FAILED_USER_CHANGE_PASSWORD";
export const REQUEST_USER_ACCOUNT_ACTIVATION =
  "REQUEST_USER_ACCOUNT_ACTIVATION";
export const SUCCESS_USER_ACCOUNT_ACTIVATION =
  "SUCCESS_USER_ACCOUNT_ACTIVATION";
export const FAILED_USER_ACCOUNT_ACTIVATION = "FAILED_USER_ACCOUNT_ACTIVATION";
export const REQUEST_USER_PROFILE_DETAILS = "REQUEST_USER_PROFILE_DETAILS";
export const SUCCESS_USER_PROFILE_DETAILS = "SUCCESS_USER_PROFILE_DETAILS";
export const FAILED_USER_PROFILE_DETAILS = "FAILED_USER_PROFILE_DETAILS";
export const REQUEST_UPDATE_PROFILE_INFO = "REQUEST_UPDATE_PROFILE_INFO";
export const SUCCESS_UPDATE_PROFILE_INFO = "SUCCESS_UPDATE_PROFILE_INFO";
export const FAILED_UPDATE_PROFILE_INFO = "FAILED_UPDATE_PROFILE_INFO";
export const REQUEST_COUNTRY_LIST = "REQUEST_COUNTRY_LIST";
export const SUCCESS_COUNTRY_LIST = "SUCCESS_COUNTRY_LIST";
export const FAILED_COUNTRY_LIST = "FAILED_COUNTRY_LIST";
export const REQUEST_USER_GRAPH_CLICKS = "REQUEST_USER_GRAPH_CLICKS";
export const SUCCESS_USER_GRAPH_CLICKS = "SUCCESS_USER_GRAPH_CLICKS";
export const FAILED_USER_GRAPH_CLICKS = "FAILED_USER_GRAPH_CLICKS";
export const REQUEST_USER_GRAPH_EARNINGS = "REQUEST_USER_GRAPH_EARNINGS";
export const SUCCESS_USER_GRAPH_EARNINGS = "SUCCESS_USER_GRAPH_EARNINGS";
export const FAILED_USER_GRAPH_EARNINGS = "FAILED_USER_GRAPH_EARNINGS";
export const REQUEST_USER_PAYMENT_EMAIL_VERIFY =
  "REQUEST_USER_PAYMENT_EMAIL_VERIFY";
export const SUCCESS_USER_PAYMENT_EMAIL_VERIFY =
  "SUCCESS_USER_PAYMENT_EMAIL_VERIFY";
export const FAILED_USER_PAYMENT_EMAIL_VERIFY =
  "FAILED_USER_PAYMENT_EMAIL_VERIFY";
